function [fitresult, gof] = spectrum_Fit1(F, Power_y_modi)
%CREATEFIT1(F,POWER_Y_MODI)
%  Create a fit.
%
%  Data for 'spectrum' fit:
%      X Input : F
%      Y Output: Power_y_modi
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Dec-2014 14:31:32


%% Fit: 'spectrum'.
[xData, yData] = prepareCurveData( F, Power_y_modi );

% Set up fittype and options.
ft = fittype( 'a/(1+(x/c)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [10 0];
opts.StartPoint = [24 1e-06];
opts.Upper = [50 1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'spectrum' );
h = plot( fitresult, xData, yData );
legend( h, 'Power_y_modi vs. F', 'spectrum', 'Location', 'NorthEast' );
% Label axes
xlabel( 'F' );
ylabel( 'Power_y_modi' );
grid on


